/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Rachael
 */
public class Home extends javax.swing.JPanel {

    private View view;

    /**
     * Creates new form Home
     */
    public Home(View v) {
        initComponents();
        this.view = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonProceed = new javax.swing.JButton();
        labelN = new javax.swing.JLabel();
        comboBoxProses = new javax.swing.JComboBox<>();
        labelProses = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        textFieldN = new javax.swing.JTextField();

        buttonProceed.setText("Proceed");
        buttonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProceedActionPerformed(evt);
            }
        });

        labelN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelN.setText("Number of N that is used:");

        comboBoxProses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encryption", "Decryption" }));

        labelProses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelProses.setText("Please select process:");

        labelJudul.setFont(new java.awt.Font("Yu Mincho Light", 1, 18)); // NOI18N
        labelJudul.setText("Natural Image Based Visual Secret Sharing");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonProceed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxProses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldN))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelJudul)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProses)
                    .addComponent(comboBoxProses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelN)
                    .addComponent(textFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(buttonProceed)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProceedActionPerformed
        // TODO add your handling code here:
        String process = comboBoxProses.getSelectedItem().toString();
        if (!textFieldN.getText().isEmpty()) {
            try {
                this.view.setValueN(Integer.parseInt(textFieldN.getText()));
                if (process.equalsIgnoreCase("encryption")) {
                    this.view.setPane(2);
                } else {
                    this.view.setPane(3);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "The input N value is not an Integer");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in value of N that is used");
        }
    }//GEN-LAST:event_buttonProceedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProceed;
    private javax.swing.JComboBox<String> comboBoxProses;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelN;
    private javax.swing.JLabel labelProses;
    private javax.swing.JTextField textFieldN;
    // End of variables declaration//GEN-END:variables
}
